fux ci cd pipeline yaml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,8 +1,14 @@
-name: My First CI Pipeline
+name: CI + CD Pipeline
 
 on:
   push:
-    branches: [ "main" ]
+    branches:
+      - main
+
+permissions:
+  contents: read
+  pages: write
+  id-token: write
 
 jobs:
   build:
@@ -13,11 +19,23 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Check if index.html exists
-  run: |
-    if [ -f index.html ]; then
-      echo "index.html found ✅"
-    else
-      echo "index.html NOT found ❌"
-      exit 1
-    fi
+        run: |
+          if [ -f index.html ]; then
+            echo "index.html found ✅"
+          else
+            echo "index.html NOT found ❌"
+            exit 1
+          fi
 
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v2
+        with:
+          path: .
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Deploy to GitHub Pages
+        uses: actions/deploy-pages@v2
