add files check to piepeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,5 +12,12 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Run simple command
-        run: echo "CI Pipeline is working 🚀"
+      - name: Check if index.html exists
+  run: |
+    if [ -f index.html ]; then
+      echo "index.html found ✅"
+    else
+      echo "index.html NOT found ❌"
+      exit 1
+    fi
+
